{% set name = "pyspark_dist_explore" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ce5316c5fbb75ff23623d3b12b22ac25c43eeb7d23ab25bc94532873311a0da

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - pandas
    - scipy
    - matplotlib

test:
  imports:
    - pyspark_dist_explore

about:
  home: https://github.com/Bergvca/pyspark_dist_explore
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: 'Pyspark_dist_explore is a plotting library to get quick insights on data in Spark DataFrames'

  description: |
    Pyspark_dist_explore is a plotting library to get quick insights on data
    in Spark DataFrames through histograms and density plots, where the heavy lifting is done in Spark.
  dev_url: https://github.com/Bergvca/pyspark_dist_explore

extra:
  recipe-maintainers:
    - bergvca
